build_vars:
  stage: .pre
  script:
    - echo DIR_TO_BE_TESTED=\"$(ls -1 -d */ )\" >> build.env
    - cat build.env
  artifacts:
    reports:
      dotenv: build.env

generate_trigger_gitlab-ci:
  stage: build
  image:
    name: bitnami/jsonnet:latest
    entrypoint: [""]
  script:
    - echo $CI_PIPELINE_SOURCE
    - echo $DIR_TO_BE_TESTED
    - jsonnet -m . --ext-str exercism_projects=${DIR_TO_BE_TESTED} --ext-str lang="$(echo $CI_PROJECT_NAME | sed -En 's/exercism-(.*)-sol/\1/p')" ".generate-config.jsonnet"
  dependencies:
    - build_vars
  artifacts:
    paths:
      - .generated-config.yml

trigger-tests:
  stage: test
  needs:
    - generate_trigger_gitlab-ci
  trigger:
    include:
      - artifact: .generated-config.yml
        job: generate_trigger_gitlab-ci
    strategy: depend
    
